using UnityEngine;

public class MoveDown : MonoBehaviour
{
    public float moveSpeed = 5f;
    public bool isEnemy = false;
    private GameManager gameManager;
    private int lastCheckedPoints = 0;

    void Start()
    {
        gameManager = GameObject.FindObjectOfType<GameManager>();
        if (gameManager == null)
        {
            Debug.LogError("GameManager bulunamad覺!");
        }
    }

    void Update()
    {
        if (gameManager != null)
        {
            int currentPoints = GameManager.instance.GetPoints();
            if (currentPoints >= lastCheckedPoints + 200)
            {
                moveSpeed += 1f; // H覺z覺 art覺r
                lastCheckedPoints = currentPoints;
            }
        }

        if (isEnemy)
        {
            transform.Translate(Vector3.forward * moveSpeed * Time.deltaTime);
        }
        else
        {
            transform.Translate(Vector3.back * moveSpeed * Time.deltaTime); // Z ekseninde geriye git
        }
    }
}